context:
  version: 0.2.0

package:
  name: boris-clip
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/b/boris-clip/boris_clip-${{ version }}.tar.gz
  sha256: 0775db115a8a47229439f51af7bb630d0a0f977c146669c2097dfdd167584041

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - boris-clip = boris_clip.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - click >=8.0
    - pandas >=1.5
    - ffmpeg

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - boris_clip
      pip_check: true
  - script:
      - boris-clip --help

about:
  summary: Extract video clips from BORIS behavioural annotation files
  description: |
    Extract video clips from BORIS behavioural annotation files. For each
    annotated bout in a BORIS file, boris-clip cuts the corresponding segment
    from your video and saves it as an individual clip. Clips are named after
    the source video, behaviour, subject, and time interval.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/roaldarbol/boris-clip
  repository: https://github.com/roaldarbol/boris-clip

extra:
  recipe-maintainers:
    - roaldarbol
